; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = serre

[env:esp32_air]
platform = espressif32@6.7.0
board = m5stick-c
framework = arduino
monitor_speed = 115200
build_src_filter = +<main_esp32_air.cpp>
lib_deps =
    knolleary/PubSubClient@^2.8
    adafruit/DHT sensor library@^1.4.4
    m5stack/M5StickC@^0.2.5

[env:esp32_sol]
platform = espressif32@6.7.0
board = m5stick-c
framework = arduino
monitor_speed = 115200
build_src_filter = +<main_esp32_sol.cpp>
lib_deps =
    knolleary/PubSubClient@^2.8
    m5stack/M5StickC@^0.2.5

[env:m5stack_gateway]
platform = espressif32@6.7.0
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
build_src_filter = +<main_m5stack.cpp>
lib_deps =
    knolleary/PubSubClient@^2.8
    m5stack/M5Stack@^0.4.6