[platformio]
src_dir = serre

[env:esp32_air]
platform = espressif32@6.7.0
board = m5stick-c
framework = arduino
monitor_speed = 115200
build_src_filter = +<main_esp32_air.cpp>
lib_deps =
    knolleary/PubSubClient@^2.8
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    m5stack/M5StickCPlus@^0.1.0

[env:esp32_sol]
platform = espressif32@6.7.0
board = m5stick-c
framework = arduino
monitor_speed = 115200
build_src_filter = +<main_esp32_sol.cpp>
lib_deps =
    knolleary/PubSubClient@^2.8
    m5stack/M5StickCPlus@^0.1.0

[env:m5stack_gateway]
platform = espressif32@6.7.0
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
build_src_filter = +<main_m5stack.cpp>
lib_deps =
    knolleary/PubSubClient@^2.8
    m5stack/M5Stack@^0.4.6