version: "3.9"

services:

  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  db:
    image: mariadb:11
    container_name: mosquitto_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: parc
      MYSQL_USER: mqttuser
      MYSQL_PASSWORD: mqttpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: ./app
    container_name: mqtt-consumer
    depends_on:
      - mqtt
      - db
    environment:
      DB_HOST: db
      DB_USER: mqttuser
      DB_PASSWORD: mqttpass
      DB_NAME: parc
      MQTT_HOST: mqtt
      MQTT_PORT: 1883

volumes:
  db_data: